### ISSUE TITLE
HTTPError: 400 Client Error: Bad Request for url: https://generativelanguage.googleapis.com/

### ISSUE THREAD

**Issue by kadarechen** [borrrrring/xcstrings#3]
一直提示HTTPError: 400 Client Error: Bad Request for url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=*****（我的key）

尝试新注册了一个key依然跑不通。终端可以正常ping通google.com以及generativelanguage.googleapis.com，是我的网络问题吗？

**Comment by kadarechen** [comment]
Keep showing HTTPError: 400 Client Error: Bad Request for url:  https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=***** (My api key)

Tried to register a new api key but had no luck. I can ping google.com and generativelanguage.googleapis.com perfectly in the terminal, is it my network problem?

**Comment by kadarechen** [comment]
Sorry, my mistake. I should have used a US proxy instead of a Singapore one. For anyone who might face the same issue…

**Comment by borrrrring** [comment]
Hey, bro  @kadarechen ! you can use this [api-proxy](https://github.com/TheRamU/api-proxy) project easy to use Gemini😁
